services:
  GepurIt\ErpTaskBundle\CurrentTaskMarker\CurrentTaskMarker:
    autowire: true
  GepurIt\ErpTaskBundle\CurrentTaskMarker\CurrentTaskMarkerInterface:
    alias: GepurIt\ErpTaskBundle\CurrentTaskMarker\CurrentTaskMarker
  GepurIt\ErpTaskBundle\TaskProvider\BaseTaskProvider:
    autowire: true
  GepurIt\ErpTaskBundle\CallTaskSource\ProducerToManagerRelationProvider:
    autowire: true
  GepurIt\ErpTaskBundle\ActionProcessor\BaseActionProcessor:
    autowire: true
  GepurIt\ErpTaskBundle\ActionProcessor\BaseActionProcessorInterface:
    alias: GepurIt\ErpTaskBundle\ActionProcessor\BaseActionProcessor
  GepurIt\ErpTaskBundle\ActionProcessor\ActionProcessorRegistry:
    autowire: true
  GepurIt\ErpTaskBundle\TaskPresenter\TaskPresenterRegistry:
    autowire: true
  GepurIt\ErpTaskBundle\Dynamic\DynamicSourceProviderRegistry:
     autowire: true
