services:
  GepurIt\ErpTaskBundle\TaskMarker\TaskMarker:
    autowire: true
  GepurIt\ErpTaskBundle\TaskMarker\TaskMarkerInterface:
    alias: GepurIt\ErpTaskBundle\TaskMarker\TaskMarker
  GepurIt\ErpTaskBundle\TaskProvider\BaseTaskProvider:
    autowire: true
    public: true
  GepurIt\ErpTaskBundle\Binding\ProducerToManagerRelationProvider:
    autowire: true
  GepurIt\ErpTaskBundle\ActionProcessor\BaseActionProcessor:
    autowire: true
  GepurIt\ErpTaskBundle\ActionProcessor\BaseActionProcessorInterface:
    alias: GepurIt\ErpTaskBundle\ActionProcessor\BaseActionProcessor
