services:
  GepurIt\ErpTaskBundle\CurrentTaskMarker\CurrentTaskMarker:
    autowire: true
  GepurIt\ErpTaskBundle\CurrentTaskMarker\CurrentTaskMarkerInterface:
    alias: GepurIt\ErpTaskBundle\CurrentTaskMarker\CurrentTaskMarker
  GepurIt\ErpTaskBundle\TaskProvider\BaseTaskProvider:
    autowire: true
    public: true
  GepurIt\ErpTaskBundle\Binding\ProducerToManagerRelationProvider:
    autowire: true
  GepurIt\ErpTaskBundle\ActionProcessor\BaseActionProcessor:
    autowire: true
  GepurIt\ErpTaskBundle\ActionProcessor\BaseActionProcessorInterface:
    alias: GepurIt\ErpTaskBundle\ActionProcessor\BaseActionProcessor
  GepurIt\ErpTaskBundle\ActionProcessor\ActionProcessorRegistry:
    autowire: true
